[env.production]
KV_NAMESPACES = [
  { binding = "IP_BLACKLIST", id = "YOUR_KV_NAMESPACE_ID_HERE" }
]

[env.preview]
KV_NAMESPACES = [
  { binding = "IP_BLACKLIST", id = "YOUR_KV_NAMESPACE_ID_HERE" }
]

[build]
command = ""
output_directory = "/" 