name = "ip-blacklist"
compatibility_date = "2023-12-01"
workers_dev = true

# Pages配置
pages_build_output_dir = "."

[site]
bucket = "."

[build]
command = ""

# KV命名空间绑定
kv_namespaces = [
  { binding = "IP_BLACKLIST", id = "YOUR_KV_NAMESPACE_ID_HERE" }
] 